# Generated by Django 5.0.6 on 2025-10-20 14:35

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoeco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='site',
            name='lat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(16.5), django.core.validators.MaxValueValidator(26.6)]),
        ),
        migrations.AlterField(
            model_name='site',
            name='lon',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(51.8), django.core.validators.MaxValueValidator(60.5)]),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(check=models.Q(('lat__gte', 16.5), ('lat__lte', 26.6), ('lon__gte', 51.8), ('lon__lte', 60.5)), name='chk_site_in_oman_bounds'),
        ),
    ]
