# Generated by Django 5.0.6 on 2025-10-20 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoeco', '0002_alter_alert_created_at_alter_site_lat_alter_site_lon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('air_quality_index', models.FloatField()),
                ('water_tds', models.FloatField()),
                ('rehabilitation_progress', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_forecasts', to='geoeco.site')),
            ],
            options={
                'unique_together': {('site', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ForecastProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_forecasts', to='geoeco.site')),
            ],
            options={
                'unique_together': {('site', 'year')},
            },
        ),
    ]
